ARGOeu/argo-streaming

bin/metric-publisher.py
Implement a client utility which will open consumer metric data files (.avro) and publish rows to an AMS endpoint
- metric_publisher is a simple python client that opens a consumer metric data avro file and iteratively publishes each row to a remote AMS endpoint
- cli parameters supported:
-f, --file : consumer avro file
-e, --endpoint : ams endpoint
-k, --key  :ams key(token)
-p, --project : ams project
-t, --topic : ams topic
=> ARGO-625 Python client to publish consumer metric data to AMS

flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs/batch_status/src/main/java/argo/batch/CalcStatusEndpoint.java, flink_jobs/batch_status/src/main/java/argo/batch/CalcStatusService.java
=> ARGO-809 Implement Calculation of Service Status timelines

flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs/batch_status/src/main/java/argo/batch/PickEndpoints.java, flink_jobs/batch_status/src/main/java/ops/OpsManager.java, flink_jobs/batch_status/src/main/java/sync/RecomputationsManager.java
Add a monitoring engine exclusion step in flink pipeline
=> ARGO-825 Add Mon-engine exclusion mechanism to status batch-job

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java, flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java, flink_jobs/batch_ar/src/main/java/argo/batch/MonTimeline.java, flink_jobs/batch_ar/src/main/java/argo/batch/PickEndpoints.java, flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java, flink_jobs/batch_ar/src/test/java/argo/batch/MonTimelineTest.java, flink_jobs/batch_ar/src/test/java/sync/RecomputationManagerTest.java
=> ARGO-895 Create Metric Timelines

flink_jobs/stream_status/pom.xml, flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/SyncData.java, flink_jobs/stream_status/src/main/java/argo/streaming/SyncParse.java, flink_jobs/stream_status/src/main/java/status/StatusManager.java
ClassCast Exceptions on Avro Objects when re-submitting job in flink cluster.
- Identical Cached Avro related classes were loaded by different classloaders in flink -- this resulted in ClassCast Exceptions. 
- Use a new instance of SpecificData on each AvroReader Instantiation
- Align flink version in pom file with cluster's
- Raise a runtime exception when a piece of irrelevant metric data (which should be filtered) is presented in status computation
=> ARGO-970 Fix Avro ClassCast Issue

flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java
Bucket Sink uses a default inactivity interval of 1 min and creates a new bucket(file).
Ams publisher sends metric data in intervals of ~5min thus having the hdfs sink creating small files due to inactivity threshold
Raise inactivity threshold to a greater value (30mins)
=> ARGO-988 BucketSink: Inacticity threshold increase to 30 minutes

.travis.yml, bin/test_ar_job_submit.py, bin/test_metric_ingestion_submit.py, bin/test_sync_ingestion_submit.py
Issue
-------
pytests currently run only with pytest is invoked from ./bin folder
Fix
----
Add reference to config template relative to path of each test file
=> ARGO-1074 Add reference to config template relative to each test file

README.md, flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java, flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java, flink_jobs/batch_ar/src/main/java/ops/ConfigManager.java, flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs/batch_status/src/main/java/argo/batch/PickEndpoints.java, flink_jobs/batch_status/src/main/java/ops/ConfigManager.java, flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/ops/ConfigManager.java
Add consistent and verbose names to batch and streaming status flink jobs
- Refactor ArgoBatchAr main method to add job description 
- Refactor ArgoBatchStatus main method to add job description 
- Refactor AmsStreamStatus main method to add job description 
- Update readme
- Minor fix on Ingest metric job name
- Fix read report-id parameter in Batch Status job 
- Fix read endpoint group type parameter in Batch Status job
- Minor comment fixes
=> ARGO-1073 Add more verbose names to flink jobs

README.md, flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java, flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/ArgoMessagingClient.java, flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/AmsIngestSync.java, flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/ArgoMessagingClient.java, flink_jobs/stream_status/pom.xml, flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java, flink_jobs/stream_status/src/main/java/argo/streaming/MongoStatusOutput.java, flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java, flink_jobs/stream_status/src/main/java/status/StatusEvent.java, flink_jobs/stream_status/src/main/java/status/StatusManager.java, flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java
- Issues in event generation for endpoints that belonged to multiple top level groups
- Better handling needed for controlling event timeouts for notification regeneration
- Refactor StatusManager to properly support event generation for all top-level groups that an endpoint metric check affects
- Refactor StatusManager to accept a timeout parameter with default value of 84000000ms (1day). Events generate if status change or time duration > timeout 
If an event is regenerated (due to timeout)
=> Fix event generation for services that belong to multipe groups

bin/ar_job_submit.py, bin/status_job_submit.py, bin/stream_status_job_submit.py
Report names won't always be in a strict format having Capital first-letter.
=> ARGO-1221 Report name capitalization fix

bin/ar_job_submit.py, bin/status_job_submit.py, bin/utils/test_update_profiles.py, bin/utils/update_profiles.py, conf/conf.template, docs/update_profiles.md
Implement script to check argo profile files stored in hdfs destination against argo profiles defined in argo-web-api. If hdfs ones are out-of-date upload latest argo-web-api profile definitions to hdfs
- Implement update_profiles.py script
- Implement ArgoApiClient class which contacts argo-web-api
- Implement HdfsReader class which checks files on hdfs 
- Implement ArgoProfileManager class which uses the above classes and compares the profiles between api <--> hdfs 
- Add unit tests
- Add doc
=> ARGO-1230 Fetch latest ops profile from argo-web-api

bin/utils/test_update_profiles.py, bin/utils/update_profiles.py, docs/update_profiles.md
Fetch the latest report configuration from argo-web-api and compare it against the report cfg file at hdfs. If the report file at hdfs is out-of-date replace it with.
=> ARGO-1233 Fetch latest report cfg from argo-web-api

bin/ar_job_submit.py, bin/status_job_submit.py, bin/utils/update_profiles.py, docs/update_profiles.md
Check and update local threhsolds profiles from argo-web-api definitions
=> ARGO-1277 Check and update thresholds profiles from argo-web-api

flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs/batch_status/src/main/java/argo/batch/CalcPrevStatus.java, flink_jobs/batch_status/src/main/java/argo/batch/FillMissing.java, flink_jobs/batch_status/src/main/java/argo/batch/MongoStatusOutput.java
Fix:
1) Populate an initial dataset with missing statuses for all topology elements (FillMissing operator)
2) Combine latest statues from previous day along with current day's statuses into one dataset
3) Compare the above datasets to find the real missing elements
Additiional fixes:
1) Fix mongo field name `previousTS --> previousTimestamp`
2) For newly generated `MISSING` data calculate correctly the `dateInt` and `timeInt` indexing fields
=> ARGO-1319 Fix missing status generation issue in batch status job

bin/stream_status_job_submit.py, bin/utils/argo_config.py, bin/utils/test_update_profiles.py, bin/utils/update_profiles.py, conf/argo-streaming.conf, conf/conf.template, conf/config.schema.json
:warning: __Note__: to be merged right after https://github.com/ARGOeu/argo-streaming/pull/81
Configuration manager in argo engine should be able to contact argo-web-api and retrieve a list of available tenants. The configuration should be updated with the retrieved list of tenants
=> ARGO-1287 Update tenant list from argo-web-api

bin/requirements.txt, bin/utils/argo_config.py, bin/utils/test_update_ams.py, bin/utils/update_ams.py, conf/argo-streaming.conf, conf/conf.template, conf/config.schema.json, docs/update_ams.md
:warning: __Note__: branched from https://github.com/ARGOeu/argo-streaming/pull/84 
Given tenant list from argo configuration, argo engine should be able to check in AMS endpoint if all the necessary projects/topics/subscriptions and users have been created. If item are missing argo-engine should attempt to automatically create them using a specific naming scheme (as described in docs)
=> ARGO-1292 Update AMS project from argo-web-api tenant info

bin/utils/check_tenant.py, bin/utils/update_ams.py, docs/check_tenant.md
To be merged after: https://github.com/ARGOeu/argo-streaming/pull/88
Add the ability to upload tenant's argo-engine status to argo-web-api 
- Add method to get tenant uuids from argo-web-api
- Add method to upload tenant's json status report to argo-web-api endpoint
- Break status report to individual json status reports for each tenant
- Update docs
=>  ARGO-1298 Upload tenant configuration status to argo-web-api

bin/ar_job_submit.py, bin/status_job_submit.py, bin/stream_status_job_submit.py, bin/utils/argo_mongo.py, bin/utils/recomputations.py, bin/utils/update_profiles.py, conf/conf.template, conf/config.schema.json, docs/recomputations.md
Handling of re-computations in streaming engine
=> ARGO-1291 Recomputation handling in streaming engine

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java, flink_jobs/stream_status/src/main/java/status/StatusManager.java, flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java
**Fix for devel branch**
Establish report (name & uuid) information on status-streaming job.
Decline sync files concerning other reports.
Fix: Use report-uuid instead of report name in mongo sink
=> ARGO-1402 Enable streaming-status job per report

bin/ar_job_submit.py, bin/status_job_submit.py, bin/stream_status_job_submit.py, bin/utils/test_argo_config.py, bin/utils/update_profiles.py, conf/argo-streaming.conf
- Expect {{hdfs_user}} parameter in templates instead of {{user}}
- Fix empty json array in default recomp.json generation
=> ARGO-1441 Fix hdfs_user param in config scripts

flink_jobs/batch_status/src/main/java/argo/batch/CalcStatusService.java
Bug: Engine retrieved the correct service aggregation operation from agg. profile and stored it in avOp var.  In the next step the "OR" hardcoded value was used in op selection instead of avOp. Since till now pragmatically all service aggregations resolved to "OR" this worked ok. In a scenario that some service aggregations needed "AND" this bug was quickly exposed
Use avOp result instead of "OR" when calling aggregate() method
=> ARGO-1626 Status batch service aggregation OR/AND fix

README.md, flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java
Status streaming job initializes new items with MISSING status. It  is preferable the system to be optimistic and initialize to OK instead of MISSING. 
- Change defStatus parameter to initStatus (more appropriate)
- Default initStatus to "OK" instead of "MISSING"
- Expose initStatus optionally through configuration (cli parameter --init.status)
- Update readme
=> ARGO-1581 In status streaming job use optimistically OK as init status

flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
Batch jobs don't need restart strategy. They run either by manual submission or in intervals
=> ARGO-1567 Remove restart strategy from batch jobs

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java, flink_jobs/batch_ar/src/main/java/argo/batch/CalcEndpointAR.java, flink_jobs/batch_ar/src/main/java/argo/batch/EndpointAR.java, flink_jobs/batch_ar/src/main/java/argo/batch/MongoEndpointArOutput.java, flink_jobs/batch_ar/src/main/java/argo/batch/PickEndpoints.java, flink_jobs/batch_ar/src/test/java/argo/batch/EndpointArTest.java
Add an extra layer of computations for generating a/r scores for endpoint timelines
- Add EndpointAR POJO object 
- Add CalcEndpointAR operator that accepts an endpoint timeline, calculates a/r and stores the result in an EndpointAR POJO
- Add MongoEndpointAR output operation for storing EndpointAR POJOs into a/r documents in 'endpoint_ar' mongodb collection.
- Refactor ArgoArBatch job class to include an extra step of computing and endpoint a/r data set from the already present group of endpoint timelines. Add a third mongodb destination for endpoint a/r results
- Update unit tests
=> ARGO-1679 Add batch endpoint a/r computation

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/status/StatusEvent.java, flink_jobs/stream_status/src/main/java/status/StatusManager.java, flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java
ARGO-1709 Extend status streaming job to gather status info for all group items
In case of endpoint group events provide a complete summary for the statuses of all service endpoints belonging to the group 
Extend flat status event schema with three additional aligned string arrays 
group_endpoints: is a string array with endpoint hostnames
group_services: is a string array with endpoint service types
group_statuses: is a string array with endpoint status values 
Info for each endpoint is stored inorder. For example info for 3rd endpoint is retrieved from group_endpoints[2], group_services[2] and group_statuses[2] 
Add a getGroupEndpointStatuses Method in status manager which:
--> For a specific StatusNode that is of type `endpoint_group`
---> Iterates over service node children 
----> For …
=> ARGO-1708 Extend event schema to include group item statuses

bin/ar_job_submit.py, bin/utils/argo_mongo.py
Recently added endpoint_ar data results were not handled in mongo clean scripts
- Add endpoint_ar collection reference in mongo clean script
- Add endpoint_ar  collection reference when using mongo clean logic in ar job submission script
=> ARGO-1786 Fix: mongo clean old endpoint_ar data

flink_jobs/stream_status/src/main/java/status/StatusManager.java
- Remove necessary conditionals (always true in new event generation)
- Add proper initialization for rest of top level groups in endpoint group aggregation (https://github.com/ARGOeu/argo-streaming/pull/116/commits/e3285869b2d65dc9b9918542b813dd05f7310771#diff-76f7e027324020e6a9594bac0b91cb9aR1007)
=> ARGO-1974 Fix top level aggregations in streaming event generation

flink_jobs/stream_status/src/main/java/status/StatusEvent.java, flink_jobs/stream_status/src/main/java/status/StatusManager.java, flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java
Provide a synopsis of metric statuses on each endpoint event  / notification
- Add two new array fields on the `status event` object that will hold the aligned lists of `metric names` and `metric statuses`
- Implement - in `StatusManager` - a `getMetricStatuses` function that receives an `Endpoint Node` and collects the list of metric statuses included. 
- Use `getMetricStatuses` function in main `setStatus` method when calculating the state of a known endpoint
- Update unit tests
=> ARGO-1823 Alerts add synopsis list of metrics included in endpoint

.travis.yml, bin/utils/check_tenant.py, bin/utils/update_ams.py, bin/utils/update_profiles.py, conf/config.schema.json
Use proxy options for ams and argo-web-api when node is in private network
- Add proxy and verify options in AMS and API configuration sections 
- Use proxy and verify cfg options in all utility scripts that make http calls to argo-web-api and argo messaging
=> ARGO-1931 Use proxy options in scripts for ams and web-api

bin/utils/test_update_ams.py, bin/utils/update_ams.py
Allow engine autoconfiguration routine to also setup ams users & subs related to argo archivers.
- Update `utls/update_ams.py` to look and create argo_archiver users for each tenant and archive_metric subscriptions
- Update unit tests
=> ARGO-1963 Autoconfigure archiver subs and users

bin/ar_job_submit.py, bin/status_job_submit.py, bin/stream_status_job_submit.py, bin/utils/test_update_profiles.py, bin/utils/update_profiles.py, docs/submission-scripts.md, docs/update_profiles.md
Since argo-web-api update to support historic versions in profiles such as operations, aggregations etc... argo a/r job submission script can be updated to use on demand historic version of those profiles directly from the api
Update `status_job_submit` & `status_stream_submit` scripts with optional parameter `--historic`. When `--historic` is used along with `--profile-check` `ar_job_submit` script will first retrieve the historic versions of the profiles and upload them to hdfs and then will use the correct references to them when calling status and status stream flink jobs
=> ARGO-270 Update status job submit script to optionally use historic profiles

.gitignore, flink_jobs/ams_ingest_sync/pom.xml, flink_jobs/batch_ar/pom.xml, flink_jobs/batch_status/pom.xml, flink_jobs/stream_status/pom.xml
- Bump-up junit to 4.13.1 (from 4.11)
- Bump-up xercesImpl to 2.12.0 (from 2.7.1)
- Add some eclipse project related file types to gitignore
=> Bump up depedencies according to github security check

README.md, flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/FlipFlopStatusCounter.java, flink_jobs/status_trends/src/main/java/argo/functions/LastTimeStampGroupReduce.java, flink_jobs/status_trends/src/main/java/argo/functions/StatusFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/TimelineStatusCounter.java, flink_jobs/status_trends/src/main/java/argo/functions/TopologyMetricFilter.java, flink_jobs/status_trends/src/main/java/argo/utils/Utils.java
Based on a daily report of service endpoint metric status's checks , calculate the status changes (flip flops) , rank for each status the results and display the top N service endpoint metrics enriched with group info based on reports's topology data. 
The results include only service endpoint metrics that are included in report's topology data and report's metric profile data
Added in status_trends package , all necessary classes. Execute code in BatchFlipFlopTrends class
**flink_jobs
|-- status_trends**
=> ARGO-2952 Calculate the top N flip-flopping service endpoints metrics

README.md, flink_jobs/status_trends/pom.xml, flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/FlipFlopStatusCounter.java, flink_jobs/status_trends/src/main/java/argo/functions/TimelineStatusCounter.java, flink_jobs/status_trends/src/main/java/argo/functions/TopologyMetricFilter.java
Based on  #154 #155 , write the results in the mongo db instead of the files
Implementation includes changes to BatchStatusTrends class and BatchFlipFlopTrends class , in order to connect in a mongo db, convert the results in a mongo output format and write them in mongo db
=> ARGO-2950 Write results to  mongo db

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/ArgoApiSource.java, flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java, flink_jobs/stream_status/src/main/java/argo/streaming/SyncParse.java
Use ApiResourceManager and the ArgoApiSource connector to retrieve sync information from argo-web-api during the init phase of the streaming pipeline and to provide daily (or hourly-based) updates of sync data to the streaming operators
=> ARGO-2578 Align streaming job interface to use ApiResourceManager and ArgoApiSource connector

bin/update_engine.py
`update_engine.py` runs a global auto-configuration update of the current compute engine deployment based on a argo-engine.conf file which is also updated accordingly. This is done for all tenants. We want to be able to run the global auto-configuration process optionally for one tenant updating only it's configuration section both in compute engine and in ams
Add an optional `--tenant` argument in update_engine script. Run update configuration only for the defined tenant in `--tenant` argument is provided
=> ARGO-2891 Modify update engine process to run per tenant

flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchGroupFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchServEndpFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/MapServices.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/ServiceFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/TopologyMetricFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcEndpointFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcGroupFlipFlop.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcGroupFunctionFlipFlop.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcMetricFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/pojos/GroupFunctionTrends.java, flink_jobs/status_trends/src/main/java/argo/pojos/GroupTrends.java, flink_jobs/status_trends/src/main/java/argo/profiles/AggregationProfileParser.java, flink_jobs/status_trends/src/main/java/argo/profiles/MetricProfileParser.java, flink_jobs/status_trends/src/main/java/argo/profiles/ProfilesLoader.java, flink_jobs/status_trends/src/main/java/argo/profiles/TopologyEndpointParser.java, flink_jobs/status_trends/src/main/java/argo/profiles/TopologyGroupParser.java
To calculate the satus flip flops for groups of services
Based on #168 group by group  and calculate the flip flops. **BatchGroupFlipFlopTrends class** is added to describe the jobs. 
Firstly a function is added to the results coming from the **CalcServiceFlipFlop class** computations, to descibe the group info in the aggregations profile data. This is done by **MapServices class**. 
Next data are grouped by group, function in **CalcGroupFunctionFlipFlop class** computations. Result are objects of **GroupFunctionTrends class**  
**ServiceTrends class** holds the information of the results and these are written in mongodb. **CalcServiceFlipFlop class** implements the calculation
Next data are grouped by group, calculations are made at **CalcGroupFlipFlop class**. Results are objects of …
=> ARGO-2985 Calculate flip flops for group of endpoints

README.md, flink_jobs/status_trends/pom.xml, flink_jobs/status_trends/src/main/java/argo/batch/BatchEndpointFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopCollection.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchMetricFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchServiceFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/MapServices.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/ServiceFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/TopologyMetricFilter.java, flink_jobs/status_trends/src/main/java/argo/profiles/AggregationProfileParser.java, flink_jobs/status_trends/src/main/java/argo/profiles/TopologyGroupParser.java, flink_jobs/status_trends/src/main/java/argo/utils/RequestManager.java, flink_jobs/status_trends/src/main/java/argo/utils/Utils.java, flink_jobs/status_trends/src/test/java/argo/functions/calctimelines/TimelineMergerTest.java
To collect all flip flop calculations in one job . and to define if while writing the results the collection to be written will be cleared or not
**Implementation**
**BatchFlipFlopCollection class** was added to defile all the necessary calculations . Parameter **clearMongo** was added in calculations to define if the collection will be cleared or not. if clearMongo is false or is missing the collection in mongo will remain as it is****
=> ARGO-3071 Compute all flip flop trends in one job and add a flag to clear mongo db

flink_jobs/status_trends/src/main/java/argo/batch/BatchEndpointFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopCollection.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchGroupFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchMetricFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchServiceFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroEndpointTrendsFilter.java, flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroGroupFunctionFilter.java, flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroGroupTrendsFilter.java, flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroMetricTrendsFilter.java, flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroServiceTrendsFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/TimelineMerger.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcEndpointFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcGroupFlipFlop.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcMetricFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcServiceFlipFlop.java, flink_jobs/status_trends/src/main/java/argo/pojos/MetricTrends.java, flink_jobs/status_trends/src/main/java/argo/pojos/Timeline.java
Fixes made so as results with zero flip flops are not added to total results
Also setParallelism is removed from main of the classes. The parallelism can be defined by the command running the job on cluster
Parallelism is set to 1 , in the jobs code implementation , before ranking the results. This is done in order to apply ranking on the total results and not on each one provided by each parallel execution.
=> ARGO-3152 ARGO-3153 minor fixes

flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java
Modify status trends computation to store all status results in a single collection named 'status_trends_metrics'
=> ARGO-3197 Optimize status trend metric results in single collection

flink_jobs/ams_ingest_metric/pom.xml, flink_jobs/ams_ingest_sync/pom.xml, flink_jobs/batch_ar/pom.xml, flink_jobs/batch_status/pom.xml, flink_jobs/old-models/ams_ingest_metric/pom.xml, flink_jobs/old-models/ams_ingest_sync/pom.xml, flink_jobs/old-models/batch_ar/pom.xml, flink_jobs/old-models/batch_status/pom.xml, flink_jobs/old-models/stream_status/pom.xml, flink_jobs/status_trends/pom.xml, flink_jobs/stream_status/pom.xml
Bump versions for the following dependencies:
- httpclient from 4.5.2 to 4.5.13
- xercesImpl from 2.7.1 to 2.12.0
- junit from 4.11 to 4.13.1
=> Bump dependency versions of httpclient, xerxesImpl and junit

flink_jobs/Timelines/src/main/java/timelines/Timeline.java, flink_jobs/Timelines/src/test/java/timelines/TimelineTest.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/batch/BatchTrendsCalculations.java, flink_jobs/status_trends/src/main/java/argo/batch/MongoTrendsOutput.java, flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/StatusFilter.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcEndpointFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcMetricFlipFlopTrends.java, flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcStatusTrends.java, flink_jobs/status_trends/src/main/java/argo/pojos/EndpointTrends.java, flink_jobs/status_trends/src/main/java/argo/pojos/MetricTrends.java, flink_jobs/status_trends/src/main/java/argo/status/trends/EndpointTrendsCounter.java, flink_jobs/status_trends/src/main/java/argo/status/trends/GroupTrendsCounter.java, flink_jobs/status_trends/src/main/java/argo/status/trends/MetricTrendsCounter.java, flink_jobs/status_trends/src/main/java/argo/status/trends/ServiceTrendsCounter.java, flink_jobs/status_trends/src/main/java/timelines/Timeline.java
Added to existing implementation,  the  BatchTrendsCalculations class, to calculate in one flink job, both the computations of status changes (flip flops) and computations on status appearances for CRITICAL , WARNING, UNKNOWN status , for all levels of hierarchy.
Also in Timelines Project , in Timeline class the countStatusAppearances() functions is added in order to compute the num of the appearances of a specific status on the timeline
=> ARGO-3211 Compute Status Trends for upper levels

flink_jobs/batch_ar/src/main/java/argo/amr/ApiResourceManager.java, flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java, flink_jobs/batch_status/src/main/java/argo/amr/ApiResourceManager.java, flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
Add the ability to configure timeouts when connecting to argo-web-api for fetching profiles and topology
- Add timeoutSec int parameter to ApiResourceManager class
- Use timeoutSec parameter to set requests timeouts with httpClient
- Remove unused imports in ApiResourceManager
- Add a flink job cli optional parameter "--api.timeout" in batch_status and batch_ar jobs
- Update batch_status and batch_ar argument documentation
=> ARGO-3240 Add timeout configuration when connecting to argo-web-api

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java, flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
In current argo-web-api centric jobs:
- `/flink_jobs/batch_ar/`
- `/flink_jobs/batch_status/`
there was an issue during the initialization of the jobs where the job still required a file path for the threshold profile (as used to be in hdfs) even if we parsed the information from argo-web-api. This should be removed and fixed
Remove the threshold profile initialization from file argument at the beginning of the job and check the following:
- If information coming from api includes a threshold profile initialise it with the appropriate rules given by argo-web-api response
- If not, initialise an empty threshold profile (nothing will be affected in the computation)
=> ARGO-3414 Fix thresholds init issue in batch jobs that use argo-web-api

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcEndpointTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupFunctionTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcMetricTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcServiceTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/MapServices.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/MapStatusMetricTags.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/MapTrendTags.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/MapTupleTags.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/MongoStatusOutput.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/PickEndpoints.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/StatusMetric.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/StatusTimeline.java, flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java, flink_jobs_v2/batch_status/src/main/java/flipflops/MapMetricTrends.java, flink_jobs_v2/batch_status/src/main/java/flipflops/MapServiceTrends.java, flink_jobs_v2/batch_status/src/main/java/flipflops/MetricTrends.java, flink_jobs_v2/batch_status/src/main/java/flipflops/MongoTrendsOutput.java, flink_jobs_v2/batch_status/src/main/java/flipflops/StatusAndDurationFilter.java, flink_jobs_v2/batch_status/src/main/java/flipflops/Trends.java, flink_jobs_v2/batch_status/src/main/java/trends/EndpointTrendsCounter.java, flink_jobs_v2/batch_status/src/main/java/trends/GroupTrendsCounter.java, flink_jobs_v2/batch_status/src/main/java/trends/MetricTrendsCounter.java, flink_jobs_v2/batch_status/src/main/java/trends/ServiceTrendsCounter.java
StatusMetric data are enriched with tags for each metric as they are defined in the argo-web-api. Enrichment take place at MapServices class. Mongo db output for metric levels are changed to include also the tags
=> ARGO-3424 Add tags for each metric to th mongo db output, on the calculation of status metric trends

flink_jobs_v2/batch_status/src/main/java/argo/batch/MongoStatusOutput.java
Fixed has_threshold_rule field in mongo output to be boolean instead of string . Change at MongoStatusOutput class
=> ARGO-3480 Fix has_threshold_rule to output boolean value in mongo instead of string

flink_jobs_v2/Timelines/src/main/java/timelines/TimelineAggregator.java, flink_jobs_v2/batch_status/src/main/java/argo/ar/ExcludeGroupMetrics.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcPrevStatus.java
Groups defined in recomputation request are now excluded from ar calculations, by setitng their status as unknown 
New class ExluceGroupMetric is added to do this, and also changes occured to ArgoStatusBatch class . Timeline status is filled to be unknown in TImelineAggregator class
Checks done to compare the ar calculation results with the ar results from old batch_ar job and they seem ok .
=> ARGO-3484 Exclude groups defined at recomputations from ar calculations

flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcPrevStatus.java
Metrics defined in recomputations , replace their status as EXCLUDED for the specified period, into CalcPrevStatus class.
=> ARGO-3512 Fill timeline with EXCLUDED status for excluded metric , for a specific period

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java
Fixes:
- Remove unnecessary cli arguments that shouldn't be required anymore
- Fix some cli arguments to be consistent with same arguments in batch jobs
- Fix ArrayList initialisation with sync-data from api (at the beginning of pipeline)
=> ARGO-3563 Fix cli args

flink_jobs/stream_status/src/main/java/argo/amr/ApiResourceManager.java, flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
Streaming status job failed due to timeouts when trying to retrieve topology info from argo-web-api. This was observed in tenants with large topology data.
=> ARGO-3584 Add api timeout configuration in status streaming job

flink_jobs_v2/Timelines/src/main/java/timelines/Timeline.java, flink_jobs_v2/Timelines/src/main/java/timelines/TimelineAggregator.java, flink_jobs_v2/Timelines/src/test/java/timelines/TimelineAggregatorTest.java, flink_jobs_v2/Timelines/src/test/java/timelines/TimelineTest.java, flink_jobs_v2/batch_status/src/main/java/argo/ar/CalcEndpointAR.java, flink_jobs_v2/batch_status/src/main/java/argo/ar/CalcGroupAR.java, flink_jobs_v2/batch_status/src/main/java/argo/ar/CalcServiceAR.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcEndpointTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupFunctionTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupTimeline.java, flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcServiceTimeline.java
Fix Timeline calculations to include Downtime periods . 
CalcEndpointTimeline class is affected in order to calculate the downtime of a service endpoint and include it in the timeline.
CalcEndpointAR is affected as now it is not needed to calculate the downtime period
=> ARGO-3600 Fix bug in Timelines to include DOWNTIME periods when calculated

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
-- Also: Consolidate api.proxy and ams.proxy cli parameters to one proxy parameter
ams sink didn't receive proxy=true flag when --ams.proxy parameter was present thus causing resolve exceptions when trying to execute the flink job
In the original version there was a check that added proxy flag=true to the amsMetric source
```java
if (parameterTool.has("ams.proxy")) {
String proxyURL = parameterTool.get("ams.proxy");
amsMetric.setProxy(proxyURL);
}
```
something similar is needed for the ams sink source
Also it would be nice to consolidate `--ams.proxy` and `--api.proxy` to one cli arg `--proxy`
This fix enables proxy=true flag in AMS sink when --proxy parameter is present in cli args
We have consolidated --ams.proxy and --api.proxy cli arguments to one --proxy argument
=> ARGO-3673 Enable proxy flag in ams sink when proxy cli parameter is present

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java, flink_jobs_v2/batch_multi/src/main/java/argo/batch/CalcStatusEndpoint.java, flink_jobs_v2/batch_multi/src/test/java/argo/batch/ArgoMultiJobTest.java
Fixed the missing info field to appear as field in mongo db collection. Info values were not calculated during computing endpoint status results. This is fixed now 
Changes at CalcStatusEndpoint class and ArgoMultiJob class
=> ARGO-3837 Fix missing INFO field values from status results in mongo

bin/multi_job_submit.py
Make '-x' compute cli argument optional. If not set the flink submit job does not receive any specific flags for computing ar,status,trends and instead relies on the argo-web-api to fetch the appropriate information on what to compute
=> ARGO-3912 Make multijob submit compute parameter optional

flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/TrimEvent.java
To be merged after: https://github.com/ARGOeu/argo-streaming/pull/343
Fix url handling in TrimEvent due to exceptions produced when incoming url string contained spaces
=> ARGO-3922 Fix streaming job exception when handling ui urls with spaces

flink_jobs_v2/ProfilesManager/src/main/java/profilesmanager/EndpointGroupManager.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs_v2/stream_status/src/main/java/status/StatusEvent.java, flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java
For tenants that endpoints are represented by full urls (and the hostnames are in encoded form) we need to pass and display the urls in notifications also.
=> Produce streaming events with friendly urls instead of encoded hostnames

flink_jobs_v2/batch_multi/pom.xml, flink_jobs_v2/stream_status/pom.xml
…from github
Under stream_status pom.xml dependency of xercesImpl artifact changed to v 2.12.2 , seems ok as this version does not have any vulnerabilities. Also gson artifact changes to v 2.8.9 , seems ok as it is one of the latest version of gson -could also change to the latest. 
Under batch_multi pom.xml gson artifact changes to v 2.8.9 , seems ok as it is one of the latest version of gson -could also change to the latest.
=> ARGO-3973 Change dependency versions in flink_jobs_v2 as suggested from github

flink_jobs_v2/ApiResourceManager/pom.xml, flink_jobs_v2/ProfilesManager/pom.xml, flink_jobs_v2/Timelines/pom.xml, flink_jobs_v2/ams-connector/pom.xml, flink_jobs_v2/ams_ingest_metric/pom.xml, flink_jobs_v2/ams_ingest_sync/pom.xml, flink_jobs_v2/batch_multi/pom.xml, flink_jobs_v2/pom.xml, flink_jobs_v2/stream_status/pom.xml
**Added:**
- ARGO-3984 Make streaming job initialise by default with no run.date argument and advance the subscription to the lastest message
- Write generated alerts to Ams instead of Kafka in stream_status job
- ARGO-3904 Handle repeated events such as reminders different from normal ones
**Changed:**
- ARGO-3977 Improve logs generated by the flink jobs
- ARGO-3987 Make AMS related code common in flink jobs
- ARGO-3973 update dependencies versions in flink_jobs_v2 
- ARGO-3953 Ingestion jobs should use the header ams credential method
- Streaming job doPull, doAck requests to AMS should use the header ams credential method
- ARGO-3961 Change DateTime timezone to utc during handling timestamps in Timelines and multi_job
- ARGO-3731 upgrade mongodb connector to v3.12
- Produce streaming …
=> ARGO-4131 Prepare v2.1.0 release

flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
ArgoMessagingSource was defined as a global param , initialized in main , and was wrongly used in flink functions (called directly) . This caused a NULL exception. changes made to define amr as a member of the flink functions and,  initialize it during open()
=> Fix NULL exception during using ApiResourceManager in stream status

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
in stream_status, optional parameter latest.offset (boolen) inserted to define if the ArgoMessagingSource will be initialized with runDate , or not. If ArgoMessagingSource runs with a date the the subscription's offset is modified to the offset of the start of the date. By default (in case no parameter is passed) the ArgoMessagingSource will be initialized with runDate=null and will set the offset to the latest offset of the subscription
=> ARGO-4133 AMS connector offset advancement based on date

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
There is a minor fix in AmsStreamStatus  to ensure that the parameter latest.offset  is optional, as right now if not defined at the code arises an error
=> ARGO-4143 Fix parameter latest.offset to be optional

bin/multi_job_submit.py, conf/argo-streaming.conf, conf/conf.template, conf/config.schema.json
The latest implementations for the combined reports in the multijob jar require a new argument --basispath that is used for identifying the root folder in hdfs that holds all argo tenants. This must be set up in the cli script configuration and in the multijob submit script as well
- The argument is introduced in the configuration schema file that is used to validate if our argo-streaming.conf is valid
- The argument is introduced in the sample templates
- The argument is introduced in mutijob script itself as a parameter coming from the config file. If the user has provided a `--source-data` argument different from the `tenant` value this means that the computation will run in combined mode and will need to know the root folder of argo tenants in hdfs. Thus the path_tenants parameter …
=> ARGO-4280 Introduce basispath argument in multijob submit script

bin/multi_job_submit.py, bin/test_multi_job_submit.py
Don't pass `--source-data` and `--source-topo` arguments to the sumbit command if they are not present
=> 4282 Fix source-topo and source-data arguments to be optional

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java, flink_jobs_v2/batch_multi/src/main/java/argo/batch/CalcServiceTimeline.java, flink_jobs_v2/batch_multi/src/main/java/argo/batch/FillMissing.java, flink_jobs_v2/batch_multi/src/test/java/argo/batch/ArgoMultiJobTest.java
This PR includes a fix for the issue arising for not finding services in aggregation profile, as a result of a mismatch between metric and aggregation profiles
We try catch the null exception , for null operation of the service not found in aggregation profiles and we LOG an error message
=> ARGO-4337 Handle issue for not existing service in Aggregation Profiles

.gitignore, flink_jobs_v2/ams-connector/src/main/java/ams/connector/ArgoMessagingClient.java, flink_jobs_v2/ams_ingest_metric/pom.xml, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/ArgoApiSource.java, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/IntervalType.java, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/PerformanceDataFlatMap.java, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/StatusConfig.java, flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/SyncParse.java, flink_jobs_v2/influxdb.connector/pom.xml, flink_jobs_v2/influxdb.connector/src/main/java/influxdb/connector/InfluxConnection.java, flink_jobs_v2/influxdb.connector/src/main/java/influxdb/connector/InfluxDBSink.java, flink_jobs_v2/pom.xml, flink_jobs_v2/stream_status/pom.xml, flink_jobs_v2/stream_status/src/main/java/argo/avro/MetricData.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
Containing influxdb connector, creating a sink to the influxdb
Creating performance data from actual data, of the MetricData stream and writing them as Points to influxdb
This PR is tested on a local instance of InfluxDB, so it remains as work in progress until we test to the [timeseriesdb.devel.argo.grnet.gr](http://timeseriesdb.devel.argo.grnet.gr/)
=> ARGO-4312 Ingest performance data to timeseries database

flink_jobs_v2/ProfilesManager/src/main/java/profilesmanager/DowntimeManager.java, flink_jobs_v2/ProfilesManager/src/test/java/profilesmanager/DowntimeManagerTest.java, flink_jobs_v2/batch_multi/src/main/java/argo/batch/CalcEndpointTimeline.java, flink_jobs_v2/batch_multi/src/main/java/utils/Utils.java, flink_jobs_v2/batch_multi/src/test/java/argo/batch/TestUtils.java, flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java, flink_jobs_v2/stream_status/src/main/java/sync/DowntimeCache.java, flink_jobs_v2/stream_status/src/test/java/sync/DowntimeCacheTest.java
In this PR included solutionn to handle multiple downtime periods for service endpoint.
DowntimeManager getPeriods() fixed to return a list of downtime periods.
CalcEndpointTimeline changed to handle the received list and merge it to the initial timeline
Utils added a function to merge into one, the downtime periods that are continuous.
DowntimeManagerTest change to support the implementation
=> ARGO-4732 Investigate potential issue with downtimes end and prolongue within same day

flink_jobs_v2/ams-connector/src/main/java/ams/connector/ArgoMessagingClient.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java, flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoApiSource.java, flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java
--sync.interval parameter is introduced as optional to define the interval the profiles and topology sync. 
it can be in the form of --sync.interval="1d" or "30h" or "2400m"
=> Issue with topology sync during removing APEL service from metric profiles

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java, flink_jobs_v3/batch-multi/src/main/java/argo/batch/ArgoMultiJob.java
Missing field "service" from distinct() operation on dataset resulted in wrong filtering, seemed to affect the entries of existing entries to calculate timeline. as a result previous day timestamp -data seemed to be missing and MISSING status was applied in calculations
=> ARGO-4884 Missing statuses at the beginning of day for cert validity checks
