README.md
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/status/StatusEvent.java
flink_jobs/stream_status/src/main/java/status/StatusManager.java
flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java

Add monitoring host to status event schema
Refactor status manager
Refactor status streaming job
Refactor unit tests
Update README

ARGO-727 Add monitoring host to status event schema

---

README.md
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java

ARGO-720 Store status results in hbase

---

flink_jobs/ams_stream_hbase/src/main/java/argo/streaming/AmsStreamHbase.java
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java

Refactor hbase key structure
Add report field for status results (omitted previously)

Refactor hbase keys

---

flink_jobs/stream_status/pom.xml
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java

- Dependency Fix (for resolving xerxes conflict) in pom.xml
- Minor fix in hbase fields

ARGO-229 Dependency Fix

---

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java

Remove unused kafka cli arguments from flink job
*Note: To be merged after: https://github.com/ARGOeu/argo-streaming/pull/10

ARGO-800 Remove kafka args

---

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/argo/streaming/StatusConfig.java
flink_jobs/stream_status/src/main/java/status/StatusManager.java

Generate initial statuses when the streaming job starts
Generate status results at the beginning of each day

ARGO-798 Generate status events at the start of a new day

---

README.md
flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs/batch_status/src/main/java/argo/batch/PickEndpoints.java

Set 'egroup.type' and 'datastore.uri' cli parameters as required

Make egroup.type and datastore.uri parameters required

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/PickEndpoints.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/MetricTimelineTest.java

ARGO-896 Create Endpoint Timelines

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateServiceTimeline.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceTimelineTest.java

ARGO-897 Create Service Timelines

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointGroupTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java

ARGO-898 Create Endpoint Group Timelines

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointGroupTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/ServiceAR.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceArTest.java

ARGO-899 Calculate Service AR results in flink job

---

README.md
flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcEndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointGroupTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/EndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/ServiceAR.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupArTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceArTest.java

ARGO-900 Calculate Endpoint Group AR results in flink job

---

README.md
flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcEndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointGroupTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/EndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/ServiceAR.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupArTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceArTest.java

Batch ar service datastore

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java

ARGO-902 Create Endpoint Group A/R output format to datastore

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/FillMissing.java
flink_jobs/batch_ar/src/main/java/argo/batch/ServiceAR.java
flink_jobs/batch_ar/src/main/java/ops/ConfigManager.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/EndpointGroupManager.java
flink_jobs/batch_ar/src/main/java/sync/GroupGroupManager.java
flink_jobs/batch_ar/src/main/java/sync/MetricProfileManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/main/java/sync/WeightManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupArTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/MetricTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceTimelineTest.java
flink_jobs/batch_ar/src/test/java/ops/ConfigManagerTest.java
flink_jobs/batch_ar/src/test/java/ops/DAggregatorTest.java
flink_jobs/batch_ar/src/test/java/ops/DIntergatorTest.java
flink_jobs/batch_ar/src/test/java/ops/DTimelineTest.java
flink_jobs/batch_ar/src/test/java/ops/OpsManagerTest.java
flink_jobs/batch_ar/src/test/java/sync/AggregationProfileManagerTest.java
flink_jobs/batch_ar/src/test/java/sync/GroupsOfGroupsTest.java

- Add ReduceGroupOperator for generating missing metric data
- Refactor job flow to use missing data generator
- update javadoc

ARGO-903 Implement Generator for missing statuses

---

README.md
flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcEndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateMetricTimeline.java
flink_jobs/batch_ar/src/main/java/argo/batch/FillMissing.java
flink_jobs/batch_ar/src/main/java/argo/batch/PickEndpoints.java
flink_jobs/batch_ar/src/main/java/argo/batch/ServiceAR.java
flink_jobs/batch_ar/src/main/java/ops/ConfigManager.java
flink_jobs/batch_ar/src/main/java/sync/DowntimeManager.java
flink_jobs/batch_ar/src/main/java/sync/EndpointGroupManager.java
flink_jobs/batch_ar/src/main/java/sync/GroupGroupManager.java
flink_jobs/batch_ar/src/main/java/sync/MetricProfileManager.java
flink_jobs/batch_ar/src/main/java/sync/RecomputationManager.java
flink_jobs/batch_ar/src/main/java/sync/WeightManager.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupArTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointGroupTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/EndpointTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/MetricTimelineTest.java
flink_jobs/batch_ar/src/test/java/argo/batch/ServiceTimelineTest.java
flink_jobs/batch_ar/src/test/java/ops/ConfigManagerTest.java
flink_jobs/batch_ar/src/test/java/ops/DAggregatorTest.java
flink_jobs/batch_ar/src/test/java/ops/DIntergatorTest.java
flink_jobs/batch_ar/src/test/java/ops/DTimelineTest.java
flink_jobs/batch_ar/src/test/java/ops/OpsManagerTest.java
flink_jobs/batch_ar/src/test/java/sync/AggregationProfileManagerTest.java
flink_jobs/batch_ar/src/test/java/sync/GroupsOfGroupsTest.java

- Refactor ConfigManager to be able to load report configuration through json string
- Refactor classes that used report related arguments (previously provided by individual cli parameters) to read them from ConfigManager class
- Refactor cli required arguments
- Update documentation
__note:__ to be merged after https://github.com/ARGOeu/argo-streaming/pull/30

ARGO-904 Finalize job runner class

---

flink_jobs/batch_ar/src/main/java/argo/batch/CalcEndpointGroupAR.java
flink_jobs/batch_ar/src/main/java/argo/batch/CalcServiceAR.java

Use confMgr.id instead of confMgr.report property when storing results

ARGO-923 Annotate results using report uuid instead of report name

---

README.md
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/status/StatusManager.java

- Init a flink kafka producer
- Add an additional sink using kafka producer (along with hbase)

ARGO-934 Add kafka destination to status streaming

---

flink_jobs/stream_status/src/main/java/status/StatusManager.java

Establish handling of aggregation groups (based on aggregation profile) when an endpoint group item is aggregated

ARGO-949 Fix handling of aggregation groups

---

README.md
flink_jobs/batch_ar/pom.xml
flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/MonData.java
flink_jobs/batch_ar/src/main/java/argo/batch/MongoEndGroupArOutput.java
flink_jobs/batch_ar/src/main/java/argo/batch/MongoServiceArOutput.java

- Implement Service Ar Mongo Output Format
- Implement Endpoint Group Ar Mongo Output Format
- Refactor ar batch job
- Update docs

ARGO-982 Implement and use direct MongoOutputFormat for ar batch results

---

flink_jobs/batch_ar/src/main/java/argo/batch/ArgoArBatch.java
flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointTimeline.java

- Fix downtime initialization during endpoint timeline operator 
- Fix integration of generated missing status data to the total metric data set

ARGO-1044 Fix Downtime handling in compute ar batch job

---

bin/sync_ingestion_submit.py
bin/test_metric_ingestion_submit.py
bin/test_sync_ingestion_submit.py
conf/conf.template
docs/submition-scripts.md

Functionality ready
Documentation ready
Testing ready

Sync ingestion submit script

---

bin/metric_ingestion_submit.py
bin/sync_ingestion_submit.py

When cluster has zero jobs running new job submit is skipped
Refactor job submit command scope

ARGO-1067 Fix job submit when 0 jobs run in cluster

---

.travis.yml
bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/sync_ingestion_submit.py
bin/test_ar_job_submit.py
bin/test_metric_ingestion_submit.py
bin/test_sync_ingestion_submit.py
bin/utils/argo_log.py
bin/utils/argo_mongo.py
bin/utils/common.py
conf/conf.template
docs/submission-scripts.md

Core functionality ready
Documentation ready
Test ready
Mongo clean up ready

ARGO-1040 Create A/R job submission script

---

README.md
flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs/batch_status/src/main/java/argo/batch/CalcPrevStatus.java
flink_jobs/batch_status/src/main/java/ops/ConfigManager.java

Read report-related data from report configuration site (provided as cli argument)

ARGO-1072 Batch status read report cfg

---

bin/requirements.txt
bin/status_job_submit.py
bin/test_status_job_submit.py
bin/utils/argo_mongo.py
bin/utils/common.py
conf/conf.template
docs/submission-scripts.md

Functionality ready
Documentation ready
Testing ready

ARGO-1041 Create Status job submit script

---

README.md
flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java
flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/ArgoMessagingSource.java
flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/AmsIngestSync.java
flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/ArgoMessagingSource.java
flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs/stream_status/src/main/java/argo/streaming/ArgoMessagingSource.java

Refactor AMS connector and source for: 
- optional http proxy support in AMS requests
- optional support for AMS endpoints with self-signed certs (verify on/off) 
Also:
- code cleanup (replaced deprecated methods in AMS connector)
- Updated readme

Refactor AMS source / connector to support proxy option

---

flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/SpecificAvroWriter.java

Open hdfs leases in some inactive buckets
Close writer in AvroSpecificWriter class

ARGO-1163 Fix close on Specific Avro Writer

---

bin/utils/test_update_profiles.py
bin/utils/update_profiles.py
docs/update_profiles.md

Fetch latest aggregations profile from argo-web-api and check if its aligned with the profile uploaded in hdfs. If not upload the latest one to hdfs.

ARGO-1231  ARGO-1231 Fetch latest aggregations profile from argo-web-api

---

flink_jobs/batch_ar/src/main/java/argo/batch/CreateEndpointGroupTimeline.java

Fix issue during recomputation list initialization due to omitted broadcast variable handling in operator

ARGO-1243 Fix recomputation list initialization in batch_ar

---

flink_jobs/batch_ar/src/main/java/ops/OpsManager.java
flink_jobs/batch_ar/src/main/resources/ops/EGI-algorithm.json
flink_jobs/batch_ar/src/test/java/ops/DAggregatorTest.java
flink_jobs/batch_status/src/main/java/ops/OpsManager.java
flink_jobs/stream_status/src/main/java/ops/OpsManager.java
flink_jobs/stream_status/src/main/resources/ops/EGI-algorithm.json

Refactor Operation Profile Management in flink jobs to support ops profile new schema
- Refactor read json file methods to support field name changes and json array changes

ARGO-1239 Refactor Operations Profile Manager to read new schema

---

flink_jobs/batch_ar/src/main/java/sync/AggregationProfileManager.java
flink_jobs/batch_ar/src/main/resources/ops/ap1.json
flink_jobs/batch_ar/src/main/resources/ops/ap2.json
flink_jobs/batch_status/src/main/java/sync/AggregationProfileManager.java
flink_jobs/stream_status/src/main/java/sync/AggregationProfileManager.java
flink_jobs/stream_status/src/main/resources/ops/ap1.json
flink_jobs/stream_status/src/main/resources/ops/ap2.json

Fix Aggregation Profile manager loading methods to parse new aggregation profile data from argo-web-api
Update test resources with the new aggregation profile data

ARGO-1273 Refactor aggregation profile parser

---

bin/ar_job_submit.py
bin/status_job_submit.py
docs/submission-scripts.md
flink_jobs/batch_ar/src/main/java/ops/ConfigManager.java
flink_jobs/batch_status/src/main/java/ops/ConfigManager.java

Update batch status and a/r submission scripts: 
In batch flink jobs:

ARGO-1276 Update batch submit scripts to handle threshold params

---

bin/utils/argo_config.py
bin/utils/update_profiles.py

- Update tenant report configurations. 
- Fix handling of configuration parameter that are empty lists

ARGO-1288 Update tenant reports from argo-web-api

---

bin/ar_job_submit.py
bin/status_job_submit.py
bin/stream_status_job_submit.py
bin/test_ar_job_submit.py
bin/test_status_job_submit.py
bin/test_stream_status_job_submit.py
bin/utils/argo_config.py
bin/utils/argo_mongo.py
bin/utils/test_argo_config.py
bin/utils/update_profiles.py
conf/argo-streaming.conf
conf/conf.template
conf/config.schema.json

Fix handling of report in clean mongo method
Fix handling of missing parameters in argo_config
Fix check and add default values when updating tenants
Add ability to fill-in new tenant sections 
Change handling of mongo parameters in config schema
Update unit tests

ARGO-1392 Argo engine cli script fixes

---

bin/utils/check_tenant.py
bin/utils/update_ams.py
docs/check_tenant.md

Implement cli script that check tenant's status in hdfs and ams services (if files are present, topics/subs are established and data arrived)
- Use `ArgoConfig` to get tenant_configuration 
- Use snakebite library to check hdfs destination for tenant data (metric & sync data)
- Use `ArgoAmsClient` to get tenant's ams resources (topics,subscriptions,message metrics)
- Add `get_topic_metrics` functionality to `ArgoAmsClient`
- Combine the above information in a single json report that reflects tenant's status
- Update readme
Example of tenant json report
```json
{
"engine_config": true,
"tenants": [
{
"tenant": "Foo_tenant",
"last_check": "2018-09-10T13:58:14Z",
"engine_config": true,
"hdfs": {
"metric_data": true,
"sync_data": {
"Critical": {
"downtimes": true,
"group_endpoints": true, …
```

ARGO-1290 Create tenant status check script

---

bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/status_job_submit.py
bin/sync_ingestion_submit.py
bin/test_sync_ingestion_submit.py
bin/utils/argo_config.py
bin/utils/update_ams.py
bin/utils/update_profiles.py

- Fix mongo_uri parameter handling in job submit scripts
- Fix string conversion of numeric parameters when composing shell command arguments
- Fix argo config check if top item is None before returning sub item
- Fix argo config check if iteration list value is emtpy before calculating dynamic sections
- Fix argparse typo (tenants) in status job submit script
- Fix correct tenant section to be used in sync ingestion script 
- Fix topic/subscription default names in update_ams script
- Fix hdfs-parameters handling in update profiles script
- Fix update-profiles to update profiles for all tenant's reports

ARGO-1430 Fix sync bugs in automation scripts

---

bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/status_job_submit.py
bin/sync_ingestion_submit.py
bin/test_sync_ingestion_submit.py
bin/update_engine.py
bin/utils/argo_config.py
bin/utils/update_ams.py
bin/utils/update_cron.py
bin/utils/update_profiles.py
docs/update_engine.md

:warning: __to be merged after:__ https://github.com/ARGOeu/argo-streaming/pull/94
Create a wrapper script to control the complete update for argo-engine (config, tenant profiles, ams topics/subs, cronjobs etc)

ARGO-1403 Create argo-engine update wrapper

---

bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/status_job_submit.py
bin/sync_ingestion_submit.py
bin/test_sync_ingestion_submit.py
bin/update_engine.py
bin/utils/argo_config.py
bin/utils/check_tenant.py
bin/utils/test_update_cron.py
bin/utils/update_ams.py
bin/utils/update_cron.py
bin/utils/update_profiles.py
docs/update_engine.md

:warning: __to be merged after__ https://github.com/ARGOeu/argo-streaming/pull/95

ARGO-1434 Make check tenant status look back in time for sync data

---

flink_jobs/ams_ingest_metric/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs/ams_ingest_sync/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java

In AMS client actions, when AMS api request returns an error, log the Status code and the json error object in detail

ARGO-1063 AMS Client logging on issues

---

bin/requirements.txt

ARGO-1464 Update requests dep to 2.20

---

bin/utils/argo_mongo.py

Ensure that require indexes exist in mongodb status collections when a new tenant db is created (while producing the first results)
- Add ensure_status_indexes() method in argo_mongo utility script: 
The method for a specific tenant_db checks all status_collections for the required indexes. If an index is missing from a collection it's created in the background

ARGO-1480 Argo engine automation: ensure mongodb indexes

---

bin/utils/test_update_cron.py
bin/utils/update_cron.py

Fix hourly/daily pattern mis-match in cron autoconfiguration

ARGO-164 Fix cron autoconfiguration daily/hourly mis-match

---

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs/stream_status/src/main/java/status/StatusEvent.java
flink_jobs/stream_status/src/main/java/status/StatusManager.java
flink_jobs/stream_status/src/test/java/status/StatusManagerTest.java

Forward information about metric, endpoint, service on all event levels
Forward information about monitoring summary and message

ARGO-1675 Forward metric,endpoint and service values on all event levels

---

bin/ar_job_submit.py
bin/status_job_submit.py
bin/utils/recomputations.py

- Fix re-computation filename pattern in hdfs upload methods
- Use only hdfs path when uploading instead of hdfs uri

ARGO-1740 Recomputation hdfs path fix

---

bin/stream_status_job_submit.py
bin/test_stream_status_job_submit.py
bin/utils/update_profiles.py
conf/argo-streaming.conf
conf/conf.template
conf/config.schema.json

streaming status sumbittion script needed to be updated with the latest verstion of status-streaming job
- Update cli arguments
- Use better defaults

ARGO-1980 Clean-up streaming status script submission

---

bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/status_job_submit.py
bin/stream_status_job_submit.py
bin/sync_ingestion_submit.py
bin/utils/argo_mongo.py
bin/utils/common.py

Add option to run submission scripts in --dry-run mode

 ARGO-1932 Add dry-run mode to submission scripts

---

.travis.yml
bin/ar_job_submit.py
bin/metric_ingestion_submit.py
bin/requirements.txt
bin/status_job_submit.py
bin/sync_ingestion_submit.py
bin/test_ar_job_submit.py
bin/test_metric_ingestion_submit.py
bin/test_status_job_submit.py
bin/test_stream_status_job_submit.py
bin/test_sync_ingestion_submit.py
bin/update_engine.py
bin/utils/argo_config.py
bin/utils/argo_mongo.py
bin/utils/check_tenant.py
bin/utils/common.py
bin/utils/recomputations.py
bin/utils/test_argo_config.py
bin/utils/test_update_ams.py
bin/utils/test_update_cron.py
bin/utils/test_update_profiles.py
bin/utils/update_ams.py
bin/utils/update_cron.py
bin/utils/update_profiles.py
conf/argo-streaming.conf

Update python submission and utility scripts to python 3.6

ARGO-2143 Finalize py3 version in argo-compute-engine scripts

---

flink_jobs/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java

Conditional fix: check string content for equality

ARGO-2627 Fix sync ingestion conditional in status streming job

---

bin/utils/argo_mongo.py

Ensure that indexes for sync data collections (downtimes, weights, topology etc) are applied in mongodb tenant databases

ARGO-2672 Ensure indexes are enabled for sync data

---

flink_jobs/stream_status/pom.xml

Reverts ARGOeu/argo-streaming#133

Revert "Bump xercesImpl from 2.7.1 to 2.12.0 in /flink_jobs/stream_status"

---

flink_jobs/stream_status/pom.xml

Reverts ARGOeu/argo-streaming#135

Revert "Bump junit from 4.11 to 4.13.1 in /flink_jobs/stream_status"

---

README.md
flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchServEndpFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/FlipFlopStatusCounter.java
flink_jobs/status_trends/src/main/java/argo/functions/flipfloptrends/FlipFlopStatusCounter.java
flink_jobs/status_trends/src/main/java/argo/functions/servendptrends/CalcServiceEndpointFlipFlop.java
flink_jobs/status_trends/src/main/java/argo/functions/statustrends/TimelineStatusCounter.java
flink_jobs/status_trends/src/main/java/argo/functions/timeline/CalcMetricTimelineStatus.java
flink_jobs/status_trends/src/main/java/argo/functions/timeline/LastTimeStampGroupReduce.java
flink_jobs/status_trends/src/main/java/argo/functions/timeline/StatusFilter.java
flink_jobs/status_trends/src/main/java/argo/functions/timeline/TopologyMetricFilter.java
flink_jobs/status_trends/src/main/java/argo/pojos/MetricTimelinePojo.java
flink_jobs/status_trends/src/main/java/argo/pojos/ServEndpFlipFlopPojo.java
flink_jobs/status_trends/src/main/java/argo/utils/Utils.java

Apply flip flop calculations to service , endpoint groups based on timelines of service, endpoints,metric groups (#155)
Add BatchServEndpFlipFlopTrends class and CalcServiceEndpointFlipFlop class for the computations,
Also change the datasets from tuples to pojos, so new classes are included to define the pojos.
Finally some class names changed for better description

ARGO-2953 Service endpoints flipflops

---

README.md
flink_jobs/status_trends/src/main/java/argo/batch/BatchServEndpFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/utils/RequestManager.java
flink_jobs/status_trends/src/main/java/argo/utils/Utils.java

Read operation profile truth tables from web api

ARGO-2976 read operation profile truth tables from web api

---

flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchServEndpFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/utils/RequestManager.java
flink_jobs/status_trends/src/main/java/parsers/AggregationProfileParser.java
flink_jobs/status_trends/src/main/java/parsers/GroupOps.java

Get Aggregation Profiles from web api , parse the json result and store the information
Added AggregationProfileParser class to call the request to the api, and to store the received information

ARGO-2981 Investigate and parse aggregation profiles

---

flink_jobs/status_trends/src/main/java/argo/batch/BatchGroupFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchServEndpFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchServiceFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/MapServices.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/ServiceFilter.java
flink_jobs/status_trends/src/main/java/argo/profiles/AggregationProfileParser.java

To write in the mongo db the date for which the calculations are done.
Added in **Utils class** a function to take the parameter date (which is changed to be expected as required) and display it in a **YYYY-MM-DD** format . This date is added, as a field, to the mongo entries

ARGO-3058 Add date argument to result and write to mongo

---

flink_jobs/old-models/stream_status/metric_data.avsc

Update metric data schema reference

in status-streaming job update metric data schema ref

---

flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopCollection.java

Added in BatchFlipFlopCollection ranking for all trends

Add ranking in flip flop collections

---

bin/ar_job_submit.py
bin/status_job_submit.py
bin/test_ar_job_submit.py
bin/test_status_job_submit.py
bin/utils/test_update_profiles.py
conf/conf.template
flink_jobs/stream_status/src/main/java/argo/streaming/ArgoApiSource.java

ARGO-2663 ar submit script: Use optional inputs and proper defaults in argo a/r batch computation
Update ar and status python submit scripts to handle argo-web-api related parameters and defaults and drop unused hdfs related params

ARGO-2664 status submit script: Use optional inputs and proper defaults in argo a/r batch computation.  

---

flink_jobs/status_trends/src/main/java/argo/profiles/AggregationProfileParser.java
flink_jobs/status_trends/src/main/java/argo/profiles/MetricProfileParser.java
flink_jobs/status_trends/src/main/java/argo/profiles/OperationsParser.java
flink_jobs/status_trends/src/main/java/argo/profiles/ReportParser.java
flink_jobs/status_trends/src/main/java/argo/profiles/TopologyEndpointParser.java
flink_jobs/status_trends/src/main/java/argo/profiles/TopologyGroupParser.java
flink_jobs/status_trends/src/main/resources/calctimelines/aggregation.json
flink_jobs/status_trends/src/main/resources/calctimelines/operations.json
flink_jobs/status_trends/src/test/java/argo/functions/calctimelines/TimelineMergerTest.java

Fixed unit tests
Changed classes TimelineMergerTest.class ,classes under /profiles  and json files added to 
resources to provide api request result as json

Refactor status trends unit tests

---

flink_jobs/status_trends/src/main/java/argo/profiles/AggregationProfileParser.java

Fixed bug in AggregationProfileParser to fix wrong computations on status trends

ARGO-3142 Investigate results for a specific report and fix if there are errors

---

flink_jobs/old-models/ams_ingest_sync/pom.xml

Bump missed junit dep

---

.gitignore
flink_jobs/ProfilesManager/.gitignore
flink_jobs/ProfilesManager/src/main/java/profilesmanager/MetricProfileManager.java
flink_jobs/ProfilesManager/src/main/java/profilesmanager/ReportManager.java
flink_jobs/ProfilesManager/src/main/resources/profiles/report.json
flink_jobs/ProfilesManager/src/test/java/profilesmanager/ReportManagerTest.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchEndpointFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopCollection.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchGroupFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchMetricFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchServiceFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/ServiceFilter.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcServiceFlipFlop.java
flink_jobs/status_trends/src/main/java/argo/profiles/ProfilesLoader.java
flink_jobs/status_trends/src/main/java/argo/profiles/ReportManager.java
flink_jobs/status_trends/src/main/java/argo/utils/RequestManager.java

ConfigManager class is added to the ProfilesManager project , to implement the tenant's report data parsing.
Changes also occured to status_trends and batch_ar projects to migrate the new implementation and test if 
it runs smoothly.

ARGO-3206 Create Report Profile Parser independent Component

---

flink_jobs/ProfilesManager/.gitignore
flink_jobs/ProfilesManager/src/main/java/profilesmanager/EndpointGroupManager.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchFlipFlopCollection.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/filter/zero/flipflops/ZeroStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/ServiceFilter.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/TopologyMetricFilter.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcMetricFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcServiceFlipFlop.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcStatusTrends.java
flink_jobs/status_trends/src/main/java/argo/profiles/EndpointGroupManager.java
flink_jobs/status_trends/src/main/java/argo/profiles/ProfilesLoader.java
flink_jobs/status_trends/src/main/java/argo/utils/RequestManager.java
flink_jobs/status_trends/src/main/java/timelines/TimelineUtils.java

Some fixes made in EndpointGroupManager in ProfilesManager project .
Also a filter ZeroStatusTrends is added to filter status trends with zero num count per status type

Fixes in EndpointGroupManager & ZeroStatusTrends filter is added

---

flink_jobs/Timelines/src/main/java/timelines/Timeline.java
flink_jobs/Timelines/src/main/java/timelines/Utils.java
flink_jobs/Timelines/src/test/java/timelines/TimelineTest.java
flink_jobs/status_trends/src/main/java/argo/batch/BatchTrendsCalculations.java
flink_jobs/status_trends/src/main/java/argo/batch/MongoTrendsOutput.java
flink_jobs/status_trends/src/main/java/argo/batch/Trends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctimelines/StatusAndDurationFilter.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcEndpointFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/functions/calctrends/CalcMetricFlipFlopTrends.java
flink_jobs/status_trends/src/main/java/argo/pojos/MetricTrends.java
flink_jobs/status_trends/src/main/java/argo/status/trends/EndpointTrendsCounter.java
flink_jobs/status_trends/src/main/java/argo/status/trends/GroupTrendsCounter.java
flink_jobs/status_trends/src/main/java/argo/status/trends/MetricTrendsCounter.java
flink_jobs/status_trends/src/main/java/argo/status/trends/ServiceTrendsCounter.java
flink_jobs/status_trends/src/main/java/argo/utils/Utils.java
flink_jobs/status_trends/src/main/java/timelines/Timeline.java

BatchTrendsCalculations are now implemented to calculate and rank status trends by status duration.
Changes occured to classes at argo.status.trends package as well as new function countStatusDuration() was added to the
Timelines class

ARGO-3239 Implement status trends calculations based on the duration of each status appearance to the checks 

---

Jenkinsfile

Update jenkins file for running coverage tests and building artifacts for projects under `./flink_jobs_v2`

Update jenkins file for flink_jobs_v2

---

flink_jobs/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs/batch_status/src/main/java/argo/batch/CalcStatusEndpoint.java
flink_jobs/batch_status/src/main/java/argo/batch/CalcStatusService.java
flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v2/batch_status/pom.xml
flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcEndpointTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcPrevStatus.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcStatusEndpoint.java

Improvements applied for calculations of endpoint timelines, using common code .
Changes on code at CalcStatusEndpoint class

ARGO-3249 Calculate and write to mongo db status timelines for endpoints

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java

parameters calcStatus =ON/OFF and calcAR =ON/OFF added to define if calculations should take place and results should be written to db. If OFF no calculations or results are written. parameters are optional meaning that if they are not defined default value ON is in action and calculations take place by default

Add params calcStatus & calcAR to define calculations and writing output to db

---

flink_jobs_v2/Timelines/src/main/java/timelines/TimelineIntegrator.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MapMetricTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MetricTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MongoTrendsOutput.java
flink_jobs_v2/batch_status/src/main/java/flipflops/StatusAndDurationFilter.java
flink_jobs_v2/batch_status/src/main/java/flipflops/Trends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroMetricTrendsFilter.java

Flip flop calculations for metric level is added to the batch status job . New implementation under flipflops package.

ARGO-3293 Integrate flip flops of metric level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MetricTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MongoTrendsOutput.java
flink_jobs_v2/batch_status/src/main/java/trends/MetricTrendsCounter.java

Integrate trends calculations , for metric level , into the job. New code under trends package

ARGO-3294 Integrate status trends for metric level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcEndpointFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/EndpointTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MapEndpointTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MongoTrendsOutput.java
flink_jobs_v2/batch_status/src/main/java/flipflops/StatusAndDurationFilter.java
flink_jobs_v2/batch_status/src/main/java/flipflops/Trends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroEndpointTrendsFilter.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroMetricTrendsFilter.java
flink_jobs_v2/batch_status/src/main/java/trends/MetricTrendsCounter.java

Flip flop calculations for endpoint level added to job. New code under flipflops package

ARGO-3299 Integrate flip flops of endpoint level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcEndpointFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/EndpointTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroMetricTrendsFilter.java
flink_jobs_v2/batch_status/src/main/java/trends/EndpointTrendsCounter.java

Trends calculation for endpoint level added to job . New code implementation under trends package

ARGO-3300 Integrate status trends for endpoint level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcServiceFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MapServiceTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ServiceTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroServiceTrendsFilter.java

Flip flop calculations for service level added to job . New implementation under flipflops package

ARGO-3212 Integrate flip flops of service level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/trends/ServiceTrendsCounter.java

Service Trends calculations added to job. New code under trends package

ARGO-3313 Integrate status trends for service level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcEndpointFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcGroupFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/GroupTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MapGroupTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/ZeroGroupTrendsFilter.java

Flipflop calculation for group level added to job. New code under flipflop package

ARGO-3314 Integrate flip flops of group level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcEndpointFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/EndpointTrends.java
flink_jobs_v2/batch_status/src/main/java/trends/GroupTrendsCounter.java

Add trends calculations for group level. New code under trends package

ARGO-3315 Integrate status trends for group level

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcEndpointFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/EndpointTrends.java

calcFlipFlops=ON/OFF and calcTrends=ON/OFF is added as run parameters to define if the calculations of computing flipflops/trends should take place

ARGO-3399 Add parameter calcTrends=ON/OFF & calcFlipFlops=ON/OFF to define status trends and flip flops execution

---

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/RequestManager.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/PickEndpoints.java

timeout=30 seconds, increased from previous valued to flink_jobs_v2/ApiResourceManager/RequestManager
Also in ArgoStatusBatch threshold dataset changed to be retrieved from web api request and not from file, as it was since now

ApiResouceManager connection timeout increased to 30s

---

flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoStatusBatch.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcEndpointTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupFunctionTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcMetricTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcServiceTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/StatusTimeline.java
flink_jobs_v2/batch_status/src/main/java/flipflops/CalcMetricFlipFlopTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MapMetricTrends.java
flink_jobs_v2/batch_status/src/main/java/flipflops/MetricTrends.java
flink_jobs_v2/batch_status/src/main/java/trends/MetricTrendsCounter.java
flink_jobs_v2/batch_status/src/main/java/trends/StatusTrends.java

Tag addition to existing map functions instead of creating new ones

ARGO-3444 Move tags addition to existing map functions

---

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcPrevStatus.java

Fix Threshold bug in CalcPrevStatus, the bug excluded results that didnt have threshold rule applied.

Fix threshold bug

---

flink_jobs_v2/ProfilesManager/src/main/java/profilesmanager/DowntimeManager.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java
flink_jobs_v2/stream_status/src/main/java/sync/DowntimeCache.java
flink_jobs_v2/stream_status/src/test/java/sync/DowntimeCacheTest.java

DowntimeManager in ProfilesManager project is now used in stream_status. Redundant code removed in stream_status

ARGO-3465 Use DowntimeManager code in StreamStatus job

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java
flink_jobs_v2/stream_status/src/test/java/sync/DowntimeCacheTest.java

Use MetricProfileManager in ProfilesManager in stream_status and removed redundant code.

ARGO-3461 Use MetricProfileManager code in StreamStatus job

---

flink_jobs_v2/ProfilesManager/src/main/java/profilesmanager/OperationsManager.java
flink_jobs_v2/ProfilesManager/src/test/java/profilesmanager/OperationsManagerTest.java

EXCLUDED status is added to OperationsManager as an extra default status.

ARGO-3511 Add EXCLUDED status in OperationsManager

---

flink_jobs/old-models/stream_status/pom.xml
flink_jobs/stream_status/pom.xml

Bump xercesImpl to 2.12.2
After suggestions in:
https://github.com/ARGOeu/argo-streaming/pull/275
https://github.com/ARGOeu/argo-streaming/pull/276

ARGO-3580 Bump xercesImpl to 2.12.2

---

flink_jobs_v2/batch_status/pom.xml
flink_jobs_v2/batch_status/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcEndpointTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupFunctionTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcGroupTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcPrevStatus.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcServiceTimeline.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcStatusEndGroup.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcStatusEndpoint.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/CalcStatusService.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/ExcludeMetricData.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/FillMissing.java
flink_jobs_v2/batch_status/src/main/java/argo/batch/PickEndpoints.java
flink_jobs_v2/batch_status/src/test/java/argo/batch/ArgoMultiJobTest.java

Renamed project to ArgoMultiJob and also changed the main class of ArgoStatusBatch to ArgoMultiJob
Added in pom.xml a buildnumber-maven-plugin  to change the versions of the jar while build

ARGO-3579 Rename ArgoBatchStatus.jar to ArgoMultiJob

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndGroupArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndpointArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoServiceArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java

Added clearMongo to MongoStatusOutput and MongoEndpointArOutput,MongoServiceArOutput,MongoEndGroupArOutput in order to be able if the results of timelines and ar will be overwritten in mongo db

ARGO-3604 Clear Mongo DB of status timelines and AR results

---

bin/ar_job_submit.py
bin/multi_job_submit.py
bin/test_multi_job_submit.py
bin/test_status_job_submit.py
conf/conf.template
conf/config.schema.json
docs/submission-scripts.md

Add new submission script for multi job that calculates in one step ar, status and trend results

ARGO-3587 Create multi job submit script. Minor fixes in old scripts

---

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResponseParser.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/TrimEvent.java

add url history in event messages to ams

ARGO-3631 Αdd urlhistory to message

---

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResponseParser.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/TrimEvent.java

add url help to event messages to ams

ARGO-3632 Add urlhelp to message

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/TrimEvent.java

fix url in message

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndGroupArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndpointArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoServiceArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java
flink_jobs_v2/batch_multi/src/main/java/trends/calculations/MongoTrendsOutput.java
flink_jobs_v2/batch_multi/src/main/java/trends/status/ServiceTrendsCounter.java
flink_jobs_v2/batch_multi/src/test/java/argo/batch/ArgoMultiJobTest.java

Creates in MongoOutput , an ObjectId to represent the now time , and after writing the new results , applies a filter to delete the records existing in the collection before the now time

ARGO-3758 Implement a mechanism using ObjectId to clean the previous records

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/FillMissing.java

group name added in FillMissing class

ARGO-3848 Fix empty group name in status results

---

flink_jobs/OperationsManager/pom.xml
flink_jobs/ProfilesManager/pom.xml
flink_jobs/ams_ingest_metric/pom.xml
flink_jobs/ams_ingest_sync/pom.xml
flink_jobs/batch_ar/pom.xml
flink_jobs/batch_status/pom.xml
flink_jobs/old-models/ams_ingest_metric/pom.xml
flink_jobs/old-models/ams_ingest_sync/pom.xml
flink_jobs/old-models/batch_ar/pom.xml
flink_jobs/old-models/batch_status/pom.xml
flink_jobs/old-models/stream_status/pom.xml
flink_jobs/status_trends/pom.xml
flink_jobs/stream_status/pom.xml
flink_jobs_v2/AmsPublisher/pom.xml
flink_jobs_v2/ApiResourceManager/pom.xml
flink_jobs_v2/ProfilesManager/pom.xml

Bump gson dependencies in various flink projects to v2.8.9

ARGO-3868 Bump gson dependencies in flink projects to v2.8.9

---

flink_jobs_v2/ProfilesManager/src/main/java/profilesmanager/EndpointGroupManager.java
flink_jobs_v2/ProfilesManager/src/test/java/profilesmanager/EndpointGroupManagerTest.java
flink_jobs_v2/batch_multi/src/main/java/argo/ar/EndpointAR.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndpointArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/StatusMetric.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/TimeStatus.java
flink_jobs_v2/batch_multi/src/test/java/argo/batch/ArgoMultiJobTest.java
flink_jobs_v2/batch_multi/src/test/java/argo/batch/PickDataPointsTest.java

FIxed issue with info in results 
Main changes done to EndpointGroupManager to handle info as JsonElement and 
in MongoStatusOutput, MongoEndpointAROutput where info is parsed to be stored in mongo

ARGO-3867 Issue with argo info tags on status results when comma appears in values

---

flink_jobs_v2/AmsPublisher/pom.xml
flink_jobs_v2/ApiResourceManager/pom.xml
flink_jobs_v2/ProfilesManager/pom.xml
flink_jobs_v2/Timelines/pom.xml
flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v2/pom.xml
flink_jobs_v2/stream_status/pom.xml

- Set version of components and project to v2.0.0
- Fix Multijob label

ARGO-3916 Prepare v2.0.0 release

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java

ARGO-3921 Import fix in argo-streaming multijob

---

flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/stream_status/pom.xml

in multi_job and argo-streaming pom.xml , changed the mongo-java-driver to latest version 3.12.11

ARGO-3731 Investigate upgrading mongodb connector to v3.12

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java

In AmsStreamStatus we check if kafka parameters are defined or else if ams parameters are defined, in order to decide on which 
messaging system we publish the alerts.
--ams.alert.topic is introduced to define the topic , on which we publish the alerts in ams. 
--ams.topic is changed to ams.notification.topic , representing the topic on which we publish notifications in ams

ARGO-3978 Write generated alerts to Ams instead of Kafka in stream_status job

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSink.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSource.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/StatusConfig.java

--run.date param changed from required to optional , 
when given , offset corresponding to the specific date is received , by requesting the ams 
and then the subscription's offset is modified to this offset.
when not given the max offset is retrieved , by requesting the ams and then then the subscription's offset is modified to this offset.

ARGO-3984 Make streaming job initialise by default with no run.date argument and advance the subscription to the lastest message

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSink.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSource.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/StatusConfig.java

Reverts ARGOeu/argo-streaming#354

Revert "ARGO-3984 Make streaming job initialise by default with no run.date argument and advance the subscription to the lastest message"

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingClient.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSink.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoMessagingSource.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/StatusConfig.java

this is a v2 of the PR , due to failed build.

ARGO-3984 .v2 -Make streaming job initialise by default with no run.date argument and advance the subscription to the lastest message

---

flink_jobs_v2/ApiResourceManager/pom.xml
flink_jobs_v2/ProfilesManager/pom.xml
flink_jobs_v2/Timelines/pom.xml
flink_jobs_v2/ams-connector/pom.xml
flink_jobs_v2/ams_ingest_metric/pom.xml
flink_jobs_v2/ams_ingest_sync/pom.xml
flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/pom.xml
flink_jobs_v2/stream_status/pom.xml

Bump components and parent to v2.1.1

Bump to v2.1.1

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v2/stream_status/src/main/java/status/StatusManager.java

level_group, level_service, level_endpoint, level_metric : parameters to define the levels of alerts generated
if not defined all levels are calculated, else if ON alerts are generated and if OFF alerts are disabled for the level

ARGO-4244 In stream status introduce parameters to define the levels of the alerts to be generated

---

flink_jobs_v3/ams_ingest_metric/pom.xml
flink_jobs_v3/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java
flink_jobs_v3/pom.xml

…ed to flink 1.17
Tested locally to flink 1.17.0 cluster. 
AmsIngestJob is added as a module to flink_jobs_v3

ARGO-4257 Create flink_jobs_v3 moduled project and add modules migrated to flink 1.17

---

Jenkinsfile

Build/test v2 and v3 of flink jobs

ARGO-4260 Update jenkins build/test paths

---

flink_jobs_v2/ApiResourceManager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java

Support EOSC combined tenant 
Introduce mode=combined to the topologies request url , in order to retrieve the combined topologies for the tenant
Added new parameters to act as flags and define from where the data and topologies can be received
--source-data : all, tenant,feeds-only
--source-topo:all,tenant

ARGO-4278 Refactor multi job , to support EOSC combined mode

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java

Mini change to the path definition for a single tenant . Refactored to be as the previous version

ARGO-4278 Refactor multi job , to support EOSC combined mode -mini change

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java

Mini change to the path definition for a single tenant . Refactored to be as the previous version

Eosc combined --paths fix 

---

bin/multi_job_submit.py
bin/test_multi_job_submit.py

When submitting a multicompute job add arguments for supporting source-feeds and source-topology arguments

Update multijob to support source-data and source-topology arguments

---

flink_jobs_v3/ams-connector/pom.xml
flink_jobs_v3/ams-ingest-metric/pom.xml
flink_jobs_v3/api-resource-manager/pom.xml
flink_jobs_v3/batch-multi/pom.xml
flink_jobs_v3/profiles-manager/pom.xml
flink_jobs_v3/stream-status/pom.xml
flink_jobs_v3/timelines/pom.xml

Upgrade log4j library to the latest version

ARGO-4286 Log4j dependency - vulnerability issue

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v3/api-resource-manager/src/main/java/argo/amr/ApiResourceManager.java
flink_jobs_v3/batch-multi/src/main/java/argo/batch/ArgoMultiJob.java

Add combined tenant implementation to flink_jobs_v3

ARGO-4326 Combined tenant implementation added to batch_multi, flink_jobs_v3

---

flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java

there was an if-else that didnt permit to both write to hdfs and write to influx db. we changed this

fix ingestion job to both write in hdfs and in influx db

---

flink_jobs_v2/ams_ingest_metric/src/main/java/argo/streaming/AmsIngestMetric.java

Sync topology to the date the metric data  in the case a group is not found , to catch any updates du

AROG-4451 Handle topology sync during ingestion of performance data

---

flink_jobs_v2/stream_status/src/main/java/argo/streaming/TrimEvent.java

fix broken url in trim event during generation notifications

ARGO-4558: ARGO Streaming: Fix broken History Url in Notifications

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java

StatusMetric duplicate data that exist in  dataset  before it is  calculated about the previous status (CalcPrevStatus class ) with same  "group","function","service","endpoint","metric","status","timestamp" fields are handled to keep the distinct ones.

ARGO-4615 Handle duplicate entries in dataset

---

flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndGroupArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoEndpointArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoServiceArOutput.java
flink_jobs_v2/batch_multi/src/main/java/argo/batch/MongoStatusOutput.java
flink_jobs_v2/batch_multi/src/main/java/trends/calculations/MongoTrendsOutput.java
flink_jobs_v2/stream_status/pom.xml
flink_jobs_v2/stream_status/src/main/java/argo/streaming/MongoStatusOutput.java

Required changes made to code to enhance change in mongo java driver as mongodb-driver-sync in now introduced for mongo 6.

ARGO-4659 Make flinkv2 jobs able to write to Mongo 6.0

---

flink_jobs_v3/ams-connector/pom.xml
flink_jobs_v3/ams-ingest-metric/pom.xml
flink_jobs_v3/ams-ingest-metric/src/main/java/argo/streaming/AmsIngestMetric.java
flink_jobs_v3/api-resource-manager/pom.xml
flink_jobs_v3/batch-multi/pom.xml
flink_jobs_v3/hdfs-file-merger/pom.xml
flink_jobs_v3/influxdb.connector/pom.xml
flink_jobs_v3/profiles-manager/pom.xml
flink_jobs_v3/stream-status/pom.xml
flink_jobs_v3/stream-status/src/main/java/argo/streaming/AmsStreamStatus.java
flink_jobs_v3/timelines/pom.xml

moving to flink 1.17 and hadoop 3.2.0 and java 11

ARGO-4671 Investigate moving to HDFS version compatible with flink 1.17

---

bin/utils/test_update_ams.py
bin/utils/update_ams.py

Update `./bin/utils/update_ams.py` script to use the x-api-key header

update script for ams configuration

---

flink_jobs_v2/batch_multi/src/main/java/argo/batch/ArgoMultiJob.java
flink_jobs_v2/stream_status/src/main/java/argo/streaming/ArgoApiSource.java

Reverts ARGOeu/argo-streaming#435

Revert "ARGO-4949 Set argo-web-api verify to false for multijob and streaming…"

---

flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/stream_status/pom.xml

use mongo 3.x driver in multijob

use mongo 3.x driver in multijob

---

.gitignore
CHANGELOG.md
flink_jobs_v2/ApiResourceManager/pom.xml
flink_jobs_v2/ProfilesManager/pom.xml
flink_jobs_v2/Timelines/pom.xml
flink_jobs_v2/ams-connector/pom.xml
flink_jobs_v2/ams_ingest_metric/pom.xml
flink_jobs_v2/ams_ingest_sync/pom.xml
flink_jobs_v2/batch_multi/pom.xml
flink_jobs_v2/influxdb.connector/pom.xml
flink_jobs_v2/pom.xml
flink_jobs_v2/stream_status/pom.xml

Prep v3.0.0
